import { Injectable, Logger } from '@nestjs/common';
import * as ExcelJS from 'exceljs';
import * as PDFDocument from 'pdfkit';
import { BloodRequestEntity } from '../../blood-requests/entities/blood-request.entity';

export interface ReportMetadata {
  title: string;
  hospitalName?: string;
  hospitalId?: string;
  startDate?: Date;
  endDate?: Date;
  generatedBy: string;
}

@Injectable()
export class ReportGeneratorService {
  private readonly logger = new Logger(ReportGeneratorService.name);

  async generateBloodRequestsCSV(data: BloodRequestEntity[]): Promise<Buffer> {
    const workbook = new ExcelJS.Workbook();
    const sheet = workbook.addWorksheet('Blood Requests');

    sheet.columns = [
      { header: 'Request Number', key: 'requestNumber', width: 20 },
      { header: 'Hospital ID', key: 'hospitalId', width: 20 },
      { header: 'Status', key: 'status', width: 15 },
      { header: 'Urgency', key: 'urgency', width: 15 },
      { header: 'Required By', key: 'requiredBy', width: 25 },
      { header: 'Created At', key: 'createdAt', width: 25 },
      { header: 'Fulfillment %', key: 'fulfillment', width: 15 },
      { header: 'Items', key: 'items', width: 40 },
    ];

    data.forEach((req) => {
      const progress = req.getProgress();
      const itemsStr = req.items
        ?.map((i) => `${i.bloodType} (${i.quantityMl}ml)`)
        .join(', ');

      sheet.addRow({
        requestNumber: req.requestNumber,
        hospitalId: req.hospitalId,
        status: req.status,
        urgency: req.urgency,
        requiredBy: req.requiredByTimestamp
          ? new Date(Number(req.requiredByTimestamp)).toISOString()
          : 'N/A',
        createdAt: req.createdAt.toISOString(),
        fulfillment: `${Math.round(progress.percentage)}%`,
        items: itemsStr,
      });
    });

    return workbook.csv.writeBuffer() as Promise<Buffer>;
  }

  async generateBloodRequestsPDF(
    data: BloodRequestEntity[],
    metadata: ReportMetadata,
  ): Promise<Buffer> {
    return new Promise((resolve, reject) => {
      try {
        const doc = new PDFDocument({ margin: 50, size: 'A4' });
        const chunks: Buffer[] = [];

        doc.on('data', (chunk) => chunks.push(chunk));
        doc.on('end', () => resolve(Buffer.concat(chunks)));

        // Header
        doc
          .fillColor('#444444')
          .fontSize(20)
          .text(metadata.title, 110, 57)
          .fontSize(10)
          .text(`Hospital: ${metadata.hospitalName || metadata.hospitalId || 'All'}`, 200, 65, { align: 'right' })
          .text(`Generated by: ${metadata.generatedBy}`, 200, 80, { align: 'right' })
          .text(`Date: ${new Date().toLocaleString()}`, 200, 95, { align: 'right' })
          .moveDown();

        if (metadata.startDate || metadata.endDate) {
          const range = `Range: ${metadata.startDate?.toLocaleDateString() || '...'} to ${metadata.endDate?.toLocaleDateString() || '...'}`;
          doc.text(range, 50, 115);
        }

        doc.lineCap('butt').moveTo(50, 135).lineTo(550, 135).stroke();

        // Summary Stats
        const total = data.length;
        const fulfilled = data.filter((r) => r.isFulfilled()).length;
        const compliance = total > 0 ? (fulfilled / total) * 100 : 0;

        doc
          .fontSize(12)
          .text('Summary Statistics', 50, 150)
          .fontSize(10)
          .text(`Total Requests: ${total}`, 60, 170)
          .text(`Fulfilled: ${fulfilled}`, 60, 185)
          .text(`SLA Compliance: ${Math.round(compliance)}%`, 60, 200)
          .moveDown();

        // Table Header
        const tableTop = 230;
        doc.font('Helvetica-Bold');
        this.generateTableRow(
          doc,
          tableTop,
          'Request #',
          'Urgency',
          'Status',
          'Required By',
          'Fulfill %',
        );
        this.generateHr(doc, tableTop + 20);
        doc.font('Helvetica');

        // Table Rows
        let i = 0;
        data.forEach((req) => {
          const position = tableTop + 30 + i * 30;
          
          // Check if we need a new page
          if (position > 700) {
            doc.addPage();
            i = 0;
            // Redraw header on new page? (Keep it simple for now)
          }

          const progress = req.getProgress();
          this.generateTableRow(
            doc,
            position,
            req.requestNumber,
            req.urgency,
            req.status,
            req.requiredByTimestamp ? new Date(Number(req.requiredByTimestamp)).toLocaleDateString() : 'N/A',
            `${Math.round(progress.percentage)}%`,
          );
          this.generateHr(doc, position + 20);
          i++;
        });

        // Footer
        const range = doc.bufferedPageRange();
        for (let j = 0; j < range.count; j++) {
          doc.switchToPage(j);
          doc
            .fontSize(10)
            .text(
              `Page ${j + 1} of ${range.count}`,
              50,
              doc.page.height - 50,
              { align: 'center', width: 500 },
            );
        }

        doc.end();
      } catch (err) {
        reject(err);
      }
    });
  }

  private generateTableRow(
    doc: PDFKit.PDFDocument,
    y: number,
    id: string,
    urgency: string,
    status: string,
    requiredBy: string,
    fulfillment: string,
  ) {
    doc
      .fontSize(10)
      .text(id, 50, y)
      .text(urgency, 150, y)
      .text(status, 250, y)
      .text(requiredBy, 350, y)
      .text(fulfillment, 450, y, { align: 'right' });
  }

  private generateHr(doc: PDFKit.PDFDocument, y: number) {
    doc
      .strokeColor('#aaaaaa')
      .lineWidth(1)
      .moveTo(50, y)
      .lineTo(550, y)
      .stroke();
  }
}
