export enum IncidentRootCause {
  TRAFFIC_DELAY = 'traffic_delay',
  STOCK_MISMATCH = 'stock_mismatch',
  PROOF_FAILURE = 'proof_failure',
  TEMPERATURE_BREACH = 'temperature_breach',
  COMMUNICATION_BREAKDOWN = 'communication_breakdown',
  RIDER_NO_SHOW = 'rider_no_show',
  WRONG_DELIVERY_ADDRESS = 'wrong_delivery_address',
  RECIPIENT_UNAVAILABLE = 'recipient_unavailable',
  VEHICLE_BREAKDOWN = 'vehicle_breakdown',
  PACKAGING_FAILURE = 'packaging_failure',
  SYSTEM_ERROR = 'system_error',
  // ── Extended taxonomy ──────────────────────────────────────────────────
  SLA_BREACH = 'sla_breach',
  ANOMALY_DETECTED = 'anomaly_detected',
  COMPLIANCE_VIOLATION = 'compliance_violation',
  ESCROW_DISPUTE = 'escrow_dispute',
  COLD_CHAIN_FAILURE = 'cold_chain_failure',
  POLICY_VIOLATION = 'policy_violation',
  HUMAN_ERROR = 'human_error',
  THIRD_PARTY_FAILURE = 'third_party_failure',
  OTHER = 'other',
}
