export enum AnomalyType {
  DUPLICATE_EMERGENCY_REQUEST = 'DUPLICATE_EMERGENCY_REQUEST',
  RIDER_ROUTE_DEVIATION = 'RIDER_ROUTE_DEVIATION',
  HIGH_RIDER_CANCELLATION_RATE = 'HIGH_RIDER_CANCELLATION_RATE',
  REPEATED_ESCROW_DISPUTE = 'REPEATED_ESCROW_DISPUTE',
  SUDDEN_STOCK_SWING = 'SUDDEN_STOCK_SWING',
  MODEL_DRIFT = 'MODEL_DRIFT',
}

export enum AnomalySeverity {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
}

export enum AnomalyStatus {
  OPEN = 'OPEN',
  INVESTIGATING = 'INVESTIGATING',
  DISMISSED = 'DISMISSED',
  RESOLVED = 'RESOLVED',
}
